### ISSUE TITLE
Debug flag defaulting to true even if NODE_ENV=production

### ISSUE THREAD

**Issue by shanekenney** [hmsk/vite-plugin-elm#120]
I've noticed there's cases where the debug flag defaults to true even if `NODE_ENV` is eventually set to production by Vite. This is because defaulting the debug flag happens too early (when the plugin is loaded), before Vite has finished determining what the `NODE_ENV` is.

You can reproduce the issue by using a dotenv file to set the `NODE_ENV`, similiar to what's described in the modes section of the documentation. 

https://vitejs.dev/guide/env-and-mode.html#modes

**Comment by segmentationfaulter** [comment]
facing the same
