### ISSUE TITLE
Reference assets from elm

### ISSUE THREAD

**Issue by peacememories** [hmsk/vite-plugin-elm#178]
Hi, and thanks for maintaining this nice library :)
As web developers we often have the need for importing static assets from our code without actuallly knowing what the asset is going to be called after a build e.g. because of hashed naming).
Vitejs' approach to this is (similar to to webpack etc.) is to let users import assets as EJS modules which then resolve to a url string. Another benefit this has is that Vitejs can only package assets which are referenced by your code at the time.

I've struggled with missing this feature in Elm for a while. For webpack there is a custom loader that does this by patching the resulting js, but this is hacky and also not available in Vitejs which I like more conceptually.

I was wondering whether some form of this feature could be implemented in the elm plugin. I'm not sure yet how it would work internally, maybe using some code generation that creates a module containing functions for all the assets (this would have the benefit of allowing for code completion)

**Comment by hmsk** [comment]
Thanks for your suggestion! This is really challenging and requires a creative idea since Elm compiler and editors need to recognize assets information. In my gut, we may need an Elm package to provide a fake string or whatever about assets. At this moment, I don't have enough resource to explore the way to make this happens, so let me keep this issue opened.

**Comment by peacememories** [comment]
Hey, thanks for your answer. I agree that this is probably pretty challenging, and also doesn't have one "correct" solution. But it's a pain point I've run into a lot with elm, so I think it's worth trying to solve. I'll also probably be able to spend some time on this work-wise if we choose to adopt elm, so that's something^^

Would you mind expanding a bit on the "package to provide a fake string" idea? I'm not yet sure where you're going with this ^^'

Does the elm plugin for vite have any information at compile time about what functions got stripped from the elm codebase or something like that? That would probably help with the second part, only shipping the files that are actually used.

**Comment by loicknuchel** [comment]
Hi!
I'm looking into integrating Vite with this plugin for Azimutt (https://github.com/azimuttapp/azimutt/pull/79), but I'm also struggling with the images and all assets part :(
I'm a bit lost here so not sure I can really help but let me know if you think I can do something.

Looking for some progress :crossed_fingers:

**Comment by hmsk** [comment]
Alright! I just published an experimental feature to import vite's assets using `[ELM_VITE_PLUGIN_ASSET_PATH_DYNAMIC:/assets/logo.jpg]` or `[ELM_VITE_PLUGIN_ASSET_PATH_STATIC:../assets/logo.jpg]` (oops, I should've written `[VITE_ELM_PLUGIN...]` to consist with this plugin's name)

`..._DYNAMIC` does `import` on the top-level at once, `..._STATIC` does static filling with using [`import.meta.url`](https://vitejs.dev/guide/assets.html#the-public-directory).
See the example project's `/application/` which is demo-ing how to use this. https://github.com/hmsk/vite-plugin-elm/blob/main/example/src/Application.elm

Try with `vite-plugin-elm@2.6.0-beta.1` and I'd love to have your feedback.

For
> "package to provide a fake string" idea

I'm imagining I provide a *Elm* package to shorten this magical string so you would write `VitePluginHelper.asset('/assets/logo.jpg')` with using the package. Still TBD but this should be my next step.

**Comment by hmsk** [comment]
Had some updates (Try `vite-plugin-elm@2.6.0-beta.4`):
- Asset's tag is now `[VITE_PLUGIN_ELM_ASSET:<asset path>]`
- Released `hmsk/elm-vite-plugin-helper` to skip writing the tag

Probably this will be released as a next minor version, the feature is now documented on README: https://github.com/hmsk/vite-plugin-elm#static-assets-handling

**Comment by hmsk** [comment]
Released as `v2.6.0`
