### ISSUE TITLE
Can't get the debugging button to show up

### ISSUE THREAD

**Issue by joncol** [hmsk/vite-plugin-elm#188]
Hi, thanks for the plugin!

I'm not able to figure out why the blue Elm debugging button doesn't show up when running `yarn dev` (or `npm run dev`).

I have a minimal repository here: https://gitlab.com/joncol/hello-elm-vite/, where I'm explicitly using `{debug: true}` in the plugin options. No button shows up though...

Do you what I'm missing?

**Comment by joncol** [comment]
I had not realized that you needed the `elm/browser` library to get the debugger. Closing this.

**Comment by hmsk** [comment]
Thanks for reporting! It's just out of curiosity, is there a case of running Elm+Vite without `elm/browser`...? If the case is a thing, I'd be happy to mention about installing `elm/browser` in README or somewhere :)

**Comment by joncol** [comment]
Nah, this was just me trying to use your plugin while doing some Frontend Mentor challenges, and I was just not knowledgeable about the Elm parts. I was doing a one-off call to `view` in my `main` function. I don't think you need to document this :).
