### ISSUE TITLE
Allow multiple input files

### ISSUE THREAD

**Issue by pdamoc** [hmsk/vite-plugin-elm#217]
It would be great if the plugin could support multiple elm files. 

I'm thinking that one could use `import { Elm } from './src/Hello|Ola.elm'` in the typescript part and the plugin would compile `./src/Hello.elm` and `./src/Ola.elm` into the same output. They would then be available as `Elm.Hello` and `Elm.Ola`. 

the `node-elm-compiler` already supports multiple input files so, it looks like only a matter of turning `id` into a file list and reduce that list to the full list of dependencies.

**Comment by pdamoc** [comment]
Maybe a simpler way to declare the files would be to comma separate them like this: 
`import { Elm } from './src/Hello,./src/Ola.elm'`

**Comment by hmsk** [comment]
@pdamoc Thanks for your suggestion! I'm just curious about that the major benefits of multiple compilations. It's performant more than compiling separately or just convenient for importing into a singular object? Let me hear your use-case!

**Comment by pdamoc** [comment]
It is more performant since the so-called runtime of Elm is shared between the widgets. A more typical use-case is that of multiple Elm elements on a page. 

My use-case is a corner-case. I have a large app that is actually two sets of functionality that need to be separated. The split is quite a large refactor and the easiest way to do it is to have two entry points into the app and slowly split the functionality. This is an app that is already running in production for a very large number of users and the size of the deliverable has a direct impact on the infrastructure costs and KPIs. 

To describe my use-case with some mock code imagine the following: 

```js
Elm.FullApp.init({ flags: { product, node } });
```
```elm
view: Model -> Html msg 
view model =
    case model.product.kind of 
        Foo -> 
            renderFoo model 
        Bar -> 
            renderBar model    
```
And this needs to be transitioned to: 

```js
if(product.kind === 'Foo'){
  Elm.FooApp.init({ flags: { product, node } });
} else {
  Elm.BarApp.init({ flags: { product, node } });
}
```
In `FooApp.elm` the `view` becomes the code in `renderFoo`. In `BarApp.elm` the `view` becomes `renderBar` code. A lot of the UI and logic parts are being shared.  

This is an intermediary step with the goal that at one point the two apps would be split into separate bundling units that would be loaded conditionally by the backend server based on the `product.kind` that is also generated in the backend. 

Right now, I have three options: 
1. Different elm compilation units merged into a single bundle and pay the cost of doubling the shared code
2. Clone the project and do the backend split first rather than after 
3. Update the plugin 

I would rather avoid the first option for business performance reasons and the second option for technical coordination reasons (the backend team is overloaded at the moment) .

**Comment by hmsk** [comment]
Thanks for giving further context :) Could you give actual compilation times in you for each case (only Hello, only Ola, and both) with node-elm-compiler? I'm really interested in how multiple compilation saves resources for huge Elm apps. But basically I'm leaning toward supporting that.

My gut feeling is `import { Elm } from './src/Hello.elm?with=./src/Ola.elm,./src/Konnichiwa.elm` may be better to handle with `URLSearchParams` (and keeps validity as an URI)

**Comment by pdamoc** [comment]
Compilation times are irrelevant in my case as the elm compiler is extremely fast. For me is all about the bundle size.

I love the idea of the `id` being a relative URL. This way the `transform` function can be

```ts
    async transform(_code, id) {
      if (!id.endsWith('.elm')) return
      compilableFiles.delete(id)
    
      const idUrl = new URL(id, 'https://elm-lang.org')
      const extraIds = (idUrl.searchParams.get('with') || '').split(',')
      const ids = [idUrl.pathname, ...extraIds]

      const isBuild = process.env.NODE_ENV === 'production'
      const dependencies: string[] = await ids.reduce((acc, id) => acc.concat(compiler.findAllDependencies(id)), [])
      compilableFiles.set(id, new Set(dependencies))

      const releaseLock = await acquireLock()
      try {
        const compiled = await compiler.compileToString(ids, {
          output: '.js',
          optimize: typeof optimize === 'boolean' ? optimize : !debug && isBuild,
          verbose: isBuild,
          debug: debug ?? !isBuild,
        })

        // Apparently `addWatchFile` may not exist: https://github.com/hmsk/vite-plugin-elm/pull/36
        if (this.addWatchFile) {
          dependencies.forEach(this.addWatchFile.bind(this))
        }

        const esm = injectAssets(toESModule(compiled))

        return {
          code: isBuild ? esm : trimDebugMessage(injectHMR(esm, dependencies.map(viteProjectPath))),
          map: null,
        }
      } catch (e) {
        if (e instanceof Error && e.message.includes('-- NO MAIN')) {
          const message = `${viteProjectPath(
            id,
          )}: NO MAIN .elm file is requested to transform by vite. Probably, this file is just a depending module`
          throw message
        } else {
          throw e
        }
      } finally {
        releaseLock()
      }
    },
```

**Comment by hmsk** [comment]
Released a beta `2.7.0-beta.1` with experimental impl for multiple main files:
https://github.com/hmsk/vite-plugin-elm/releases/tag/v2.7.0-beta.1

we can use multiple input with `import { Elm } from './Application.elm?with=/Hello.elm'` (ended up with this syntax `with=./first.elm&with=./second.elm` for 3+ compilations)

could you play with this in your project @pdamoc and give your feedback?

**Comment by pdamoc** [comment]
I have tested the plugin and it works wonderfully. The only thing that was unexpected is that it threw an error if it was used like `import { Elm } from './Application.elm?with=./Hello.elm'` This can be documented but I feel like it would be better if it would be fixed by allowing both variants (i.e. check if the string starts with `./` and remove the `.` automatically).

**Comment by hmsk** [comment]
Thanks for trying right away! You found the bundle size is actually improved?

> This can be documented but I feel like it would be better if it would be fixed by allowing both variants (i.e. check if the string starts with ./ and remove the . automatically)

In current impl, I intended these two cases should be resolved differently.
For `./Application.elm?with=./Hello.elm`, `./Hello.elm` is resolved as same as `import ... from './Hello.elm'` thus the path is resolved based on the file which has this import statement. In the other hand `/Hello.elm` (no dot) will be resolved under vite's root.

I didn't have some error handlings and accurate HMR support but will work on gradually. keep eyes on updating of beta!

**Comment by pdamoc** [comment]
> You found the bundle size is actually improved?

`273.59 KiB / gzip: 91.22 KiB`  vs  `153.84 KiB / gzip: 50.95 KiB` 
 
 It actually went way better than expected.

**Comment by hmsk** [comment]
great! I believe the feature must be worth delivering!

**Comment by hmsk** [comment]
https://github.com/hmsk/vite-plugin-elm/releases/tag/v2.7.0
