### ISSUE TITLE
example app fails to build

### ISSUE THREAD

**Issue by fredcy** [hmsk/vite-plugin-elm#235]
**Describe the bug**
The example app does not build. Running `npm run dev` results in

```
failed to load config from /Users/fcy/vendor/vite-plugin-elm/example/vite.config.ts
error when starting dev server:
Error: Cannot find module '/Users/fcy/vendor/vite-plugin-elm/example/node_modules/vite-plugin-elm/dist/index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (node:internal/modules/cjs/loader:354:19)
    at Module._findPath (node:internal/modules/cjs/loader:567:18)
    at Module._resolveFilename (node:internal/modules/cjs/loader:925:27)
    at Module._load (node:internal/modules/cjs/loader:780:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/fcy/vendor/vite-plugin-elm/example/vite.config.ts:27:30)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at require.extensions.<computed> [as .ts] (/Users/fcy/vendor/vite-plugin-elm/example/node_modules/vite/dist/node/chunks/dep-88bd5805.js:61911:20)
    at Module.load (node:internal/modules/cjs/loader:981:32)
```

**Reproducible repo**
Clone this repo.  Then do:
```
cd example
npm install
npm run dev
```

**Expected behavior**
I expect vite to build the example app and start up a dev server.

**Additional context**
- version v2.7.0-beta.2-14-g05de8ab of this repo, per `git describe`
- macOS 12.3.1
- npm 8.8.0
- Elm 0.19.1

**Comment by hmsk** [comment]
Run `npm build` in the top level dir to provide `vite-plugin-elm` 😉 

I will leave about that in example's README. Thanks for reporting!

**Comment by fredcy** [comment]
I just built at the top level as described. But the example (unmodified) fails exactly as in my original report. So that still seems broken. (I recommended this plugin to an Elm developer and the first thing they did is try the example, which failed and seemed to put them off from trying this plugin)

If I edit example/package.json as suggested to set version 2.6.1 for vite-plugin-elm, then `npm run dev` does run without immediate error and I can browse the sample page. But when I click the "See Browser.element sample" link I get an error: "[plugin:vite-plugin-elm] ENOENT: no such file or directory, open '/Users/fcy/vendor/vite-plugin-elm/example/src/Description.elm?with=./AnotherDescription.elm'"

**Comment by hmsk** [comment]
Thanks for trying again!

> I just built at the top level as described. But the example (unmodified) fails exactly as in my original report. So that still seems broken.

did you run `npm install` in `/example` again then? It looks working for me 🤔 

> But when I click the "See Browser.element sample" link I get an error: "[plugin:vite-plugin-elm] ENOENT: no such file or directory, open '/Users/fcy/vendor/vite-plugin-elm/example/src/Description.elm?with=./AnotherDescription.elm'"

Ah yes, that should happen. since `Browser.element` sample only works after `2.7.0-beta.1`. I should've noted about that.

**Comment by fredcy** [comment]
It works for me today, so I must have missed a step yesterday.

Thanks for taking care of this issue.

And thanks for providing this plugin! It works great for me.
