### ISSUE TITLE
graphql gen, other preprocessors

### ISSUE THREAD

**Issue by ghost** [hmsk/vite-plugin-elm#385]
I'm curious if you would implement adding calling elm/graphql's code gen as part of this plugin or recommend defining a second vite plugin which performed that task and defined a proper ordering between the two plugins?

**Comment by hmsk** [comment]
Could you elaborate on the project's development lifecycle with elm/graphql? I have no idea about what can be supported by vite-plugin-elm. codegen part is done by just running the CLI command, and then Elm project should be rebuilt? If so, we can configure watching generated code to trigger...?

It'd be nice if you give a sample project to see how this plugin can help!

**Comment by hmsk** [comment]
I see. Probably, covering by vite-plugin-elm is out of scope I think.

[vite-plugin-run](https://github.com/innocenzi/vite-plugin-run) may be helpful to run `elm-graphql` with specific condition like every changing of `schema.json`. Then vite-plugin-elm catches the change of `.elm` files for rebuild.
