### ISSUE TITLE
Can't install the vite-plugin-elm package

### ISSUE THREAD

**Issue by JwanKhalaf** [hmsk/vite-plugin-elm#386]
**Describe the bug**
When I run `npm i -D vite-plugin-elm` as per the instructions, I get the following error:

![image](https://user-images.githubusercontent.com/42877376/208248528-6554d92d-7edb-42d4-b380-2faa61e8a8de.png)

**Reproducible repo**
Provide a link for a minimum repo to reproduce your problem in other developers local instantly. It'll be great providing screenshots/screencasts to help explain your problem.

Or clone and edit `/example` project under this plugin's repo with tests under `/cypress/integration` which fails for your expected behavior.

**Expected behavior**
Expect the package to be installed successfully.

**Comment by hmsk** [comment]
Thanks for reporting. The plugin is not supporting vite@4 yet. Give the `--force` option if you are eager to install it.

**Comment by lindsaykwardell** [comment]
Apologies for the bump, I see that Vite 4 is supported in the package.json, but not yet released to NPM. I'm curious if there's something you're waiting on before releasing the new version. Anything I can do to help get it ready for release?

**Comment by hmsk** [comment]
Uh, I missed mentioning this issue, but vite 4 is available after `2.8.0-beta.1`

**Comment by hmsk** [comment]
>  I've been using it for awhile in my project and haven't noticed any issues

Glad to hear this. I was going to have tests for new features before getting rid of "beta" but that may take more time so will work on eager/pushy 😂  releasing soon to reduce the confusion by diff between GitHub and the latest package. Thanks!
