### ISSUE TITLE
Can't take default import in ES module

### ISSUE THREAD

**Issue by simonh1000** [hmsk/vite-plugin-elm#450]
Docs say
```
import elmPlugin from 'vite-plugin-elm'

export default defineConfig({
  plugins: [elmPlugin()]
})
```

that does not work, but the example gives a clue to using `plugins: [elmPlugin.plugin()]`

**Comment by hmsk** [comment]
thanks for reporting! Can you provide a reproducible repo?

**Comment by frontmesh** [comment]
It is a typo in Readme.md 
Made a quick PR here https://github.com/hmsk/vite-plugin-elm/pull/466

**Comment by hmsk** [comment]
Updated the issue title. This problem is specific to running Vite's build as an ES module.
https://github.com/hmsk/vite-plugin-elm/pull/466#issuecomment-1523444715

**Comment by hmsk** [comment]
FYI: The next major version will be provided as pure ESM
https://github.com/hmsk/vite-plugin-elm/releases/tag/v3.0.0-0

So `import elmPlugin from 'vite-plugin-elm'` would work for projects with `"type": "module"`
