### ISSUE TITLE
virtual dom error when hot reloading

### ISSUE THREAD

**Issue by tlentz** [hmsk/vite-plugin-elm#475]
Getting virtual dom errors when hot reloading.

![image](https://github.com/hmsk/vite-plugin-elm/assets/10615259/2ef50b32-075a-481d-b32d-b482a3555f61)

**Comment by hmsk** [comment]
Thanks for the report. Please provide a reproducible repo to look into.

**Comment by tlentz** [comment]
> Thanks for the report. Please provide a reproducible repo to look into.

The only repro I have is in our large app for work. 

Ill need to see if I can get a simple repro and push it up somewhere when I find some time. 

Right now I have a theory that it has something to do with the use of Html.lazy

**Comment by tlentz** [comment]
is there a way to turn hmr off and just recompile elm/refresh the browser when detecting elm changes?

I've tried a handful of things to get a repro in a basic elm app, but cannot do so.

**Comment by hmsk** [comment]
> is there a way to turn hmr off

yea, we can disable it via vite's config.
https://vitejs.dev/config/server-options.html#server-hmr
