### ISSUE TITLE
Possible race condition that leads to a corrupt elm-stuff folder

### ISSUE THREAD

**Issue by marc136** [hmsk/vite-plugin-elm#6]
Hello @hmsk, 

I'm not sure if I should really create this as an issue because I did not reproduce this problem with vite: But the elm compiler does not like it when he runs twice at the same time on the same main elm file. It can lead to a corrupted elm-stuff folder.
So far I only reproduced this with larger code bases.

Anyway, I wanted to make you aware of this potential issue and also link you to how I solved the problem in [my snowpack plugin](https://github.com/marc136/snowpack-plugin-elm/commit/d8b2e37) in case you need it.

Cheers,
marc

**Comment by hmsk** [comment]
Thanks for the heads-up! Let me keep this issue opened until I face the problem or I take time to consider that.

**Comment by hmsk** [comment]
I finally faced to this issue frequently on GitHub Actions and solved it on #204. Thanks for your advice @marc136 🙌
