### ISSUE TITLE
Cannot find module or its corresponding type declarations

### ISSUE THREAD

**Issue by anmolitor** [hmsk/vite-plugin-elm#685]
**Describe the bug**
You get an error when you import vite-plugin-elm inside of a typescript file:
`Cannot find module 'vite-plugin-elm' or its corresponding type declarations.ts(2307)`

**Reproducible repo**
`npm i vite-plugin-elm` and `import elmPlugin from 'vite-plugin-elm'` in any .ts file should suffice.

**Expected behavior**
No error

**Additional context**
I have already opened a PR which fixed the issue by adding the "types" field to package.json.
https://github.com/hmsk/vite-plugin-elm/pull/684

**Comment by hmsk** [comment]
Released as https://github.com/hmsk/vite-plugin-elm/releases/tag/v3.0.1
Thanks for reporting/fixing!
